export const sites = [
    {
        url: 'https://amexiting.co.il/',
        property: 'Amex',
        title: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות אמריקן אקספרס',
        heading: "מאות אלפי אטרקציות וחוויות בכל העולם בהנחות מיוחדות, רק ללקוחות אמריקן אקספרס",
        carousel_heading: 'אטרקציות שאסור לפספס',
        title_en: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות אמריקן אקספרס',
        heading_en: 'Hundreds of thousands of attractions and experiences all over the world at special discounts',
        carousel_heading_en: 'Must See Attractions',
        isMerchant: true,
    },
    {
        url: 'https://isracard-fun.co.il/',
        property: 'Isracard',
        title: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות ישראכרט',
        heading: 'עשרות אלפי אטרקציות וחוויות בכל העולם בהנחות מיוחדות, רק ללקוחות ישראכרט',
        carousel_heading: 'אטרקציות שאסור לפספס',
        title_en: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות ישראכרט',
        heading_en: 'Tens of thousands of experiences all over the world with special discounts, Only for Isracard customers',
        carousel_heading_en: 'Must See Attractions',
        isMerchant: true,
    },
    {
        url: 'https://www.b321.co.il/',
        property: 'Bali',
        title: 'באלי - כרטיסים לאטרקציות בכל העולם בקליק אחד | B321',
        heading: 'מעל מיליון אטרקציות, הופעות וסיורים בעולם עכשיו עם 5% הנחה!',
        carousel_heading: 'אטרקציות שאסור לפספס',
        title_en: 'באלי - כרטיסים לאטרקציות בכל העולם בקליק אחד | B321',
        heading_en: 'Over a million attractions, performances and tours worldwide with immediate confirmation.',
        carousel_heading_en: 'Must See Attractions',
        isMerchant: true,
    },
    {
        url: 'https://www.max-adventure.co.il/',
        property: 'Max',
        title: 'Max | אתר החוויות והאטרקציות של Max',
        heading: 'כל מה שיש לעולם להציע במקום אחד, במחירים משתלמים וכ-10% קאשבק',
        carousel_heading: 'האטרקציות הכי מבוקשות',
        title_en: 'Max | אתר החוויות והאטרקציות של Max',
        heading_en: 'Everything the world has to offer in one place, at affordable prices and up to 10% cashback',
        carousel_heading_en: 'Most searched activities',
        isMerchant: false,
    },
    {
        url: 'https://pango-global-fun.pango.co.il/',
        property: 'Pango',
        title: 'פנגו גלובל פאן | מגוון הטבות לחוויות בחו"ל',
        heading: 'אתר ההטבות לחו״ל',
        carousel_heading: 'האטרקציות הכי מבוקשות',
        title_en: 'פנגו גלובל פאן | מגוון הטבות לחוויות בחו"ל',
        heading_en: 'Pango\'s worldwide',
        carousel_heading_en: 'Most searched activities',
        isMerchant: false,
    },
    {
        url: 'https://hist-travel.bridgify.io/',
        property: 'TogetherForYou',
        title: 'ביחד בשבילך | אתר החוויות והאטרקציות של ביחד בשבילך',
        heading: 'עולם שלם של חוויות במחירים מסובסדים לחברי ביחד בשבילך',
        carousel_heading: 'חוויות חורף עם ביטול גמיש',
        title_en: 'ביחד בשבילך | אתר החוויות והאטרקציות של ביחד בשבילך',
        heading_en: 'A world full of experiences at subsidized prices for "Together for you" club members',
        carousel_heading_en: 'Winter Experiences with Flexible cancellation',
        isMerchant: true,
    }
]