export const sites = [
    {
        url: 'https://amexiting.co.il/',
        title: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות אמריקן אקספרס',
        heading: "מאות אלפי אטרקציות וחוויות בכל העולם בהנחות מיוחדות, רק ללקוחות אמריקן אקספרס",
        carousel_heading: 'אטרקציות שאסור לפספס',
        title_en: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות אמריקן אקספרס',
        heading_en: 'Hundreds of thousands of attractions and experiences all over the world at special discounts',
        carousel_heading_en: 'Must See Attractions',
    },
    {
        url: 'https://www.b321.co.il/',
        title: 'באלי - כרטיסים לאטרקציות בכל העולם בקליק אחד | B321',
        heading: 'מעל מיליון אטרקציות, הופעות וסיורים בעולם עכשיו עם 5% הנחה!',
        carousel_heading: 'אטרקציות שאסור לפספס',
        title_en: 'באלי - כרטיסים לאטרקציות בכל העולם בקליק אחד | B321',
        heading_en: 'Over a million attractions, performances and tours worldwide with immediate confirmation.',
        carousel_heading_en: 'Must See Attractions',
    },
    {
        url: 'https://www.max-adventure.co.il/',
        title: 'Max | אתר החוויות והאטרקציות של Max',
        heading: 'כל מה שיש לעולם להציע במקום אחד, במחירים משתלמים וכ-10% קאשבק',
        carousel_heading: 'האטרקציות הכי מבוקשות',
        title_en: 'Max | אתר החוויות והאטרקציות של Max',
        heading_en: 'Everything the world has to offer in one place, at affordable prices and up to 10% cashback',
        carousel_heading_en: 'Most searched activities',
    },
    {
        url: 'https://isracard-fun.co.il/',
        title: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות ישראכרט',
        heading: 'עשרות אלפי אטרקציות וחוויות בכל העולם בהנחות מיוחדות, רק ללקוחות ישראכרט',
        carousel_heading: 'אטרקציות שאסור לפספס',
        title_en: 'דף הבית - אתר ההטבות לאטרקציות בחו"ל ללקוחות ישראכרט',
        heading_en: 'Tens of thousands of experiences all over the world with special discounts, Only for Isracard customers',
        carousel_heading_en: 'Must See Attractions',
    },
    {
        url: 'https://pango-global-fun.pango.co.il/',
        title: 'פנגו גלובל פאן | מגוון הטבות לחוויות בחו"ל',
        heading: 'מטיילים בחו״ל',
        carousel_heading: 'האטרקציות הכי מבוקשות',
        title_en: 'פנגו גלובל פאן | מגוון הטבות לחוויות בחו"ל',
        heading_en: 'Traveling the world',
        carousel_heading_en: 'Most searched activities',
    }
]