name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
      app_id:
        type: string
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output Branch
        run:  echo 'Branch is ${{ inputs.branch }}, ${{inputs.app_id}}'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        id: tests
        run:  INPUT_BRANCH=${{ inputs.branch }} INPUT_APP_ID=${{inputs.app_id}} npm run test:prod
      - name: Upload playwright-report
        uses: actions/upload-artifact@v4
        id: artifact-upload
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Output artifact URL
        run:  echo 'Artifact ULR is ${{ steps.artifact-upload.outputs.artifact-url }}
      - name: Output statuses
        run:  echo 'Result statuses ${{ steps.artifact-upload.outputs.artifact-url }}, ${{join(steps.tests.outputs.*, '\n')}}, ${{steps.tests.conclusion}}, ${{steps.tests.outcome}}'
